version: "3.8"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: api-db
    ports:
      - "5432:5432"
    volumes:
      - PostgresDB_Vol:/var/lib/postgresql/data
    networks:
      postgres-network:
        ipv4_address: 192.168.1.212

  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5050:80"
    volumes:
      - PGAdmin4_Vol:/var/lib/pgadmin4
      - PGAdmin_Vol:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  PostgresDB_Vol:
  PGAdmin4_Vol:
  PGAdmin_Vol:

networks:
  postgres-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

